server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      #routes:
      #  - id: PRODUCT-SERVICE
      #    uri: lb://PRODUCT-SERVICE
      #    predicates:
      #      - Path=/products/**
      #  - id: DISCOUNT-SERVICE
      #    uri: lb://DISCOUNT-SERVICE
      #    predicates:
      #      - Path=/discounts/**

      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

eureka:
  instance:
    preferIpAddress: true
    #hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoint:
    gateway:
      enabled: true